name: Test Push
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

on:
  push:
    branches: [main]
    paths:
      - "push/**"
      - ".github/workflows/test-push.yml"
  workflow_dispatch:

jobs:
  test-push:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Generate cache keys
        id: cache_keys
        working-directory: push
        run: |
          echo "python_dependencies_cache_key=CI-test-and-python-dependencies-$(sha256sum requirements.txt | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Restore cached python dependencies
        id: cache_dependencies
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cache/pip
            ~/push/.pytest_cache
          key: ${{ env.python_dependencies_cache_key }}

      - name: Install dependencies
        working-directory: push
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        working-directory: push
        run: |
          pytest

      - name: Cache python dependencies
        if: steps.cache_dependencies.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.cache/pip
            ~/push/.pytest_cache
          key: ${{ env.python_dependencies_cache_key }}
